#!/bin/sh

# Note that main.log is stored in ~/.pywikibot/logs/

cd /data/project/arkivbot
export PYTHONPATH=/shared/pywikipedia/core:/shared/pywikipedia/core/externals/httplib2:/shared/pywikipedia/core/scripts

LOG=public_html/out
STATUS=public_html/status
rm $LOG
touch $LOG

echo 'true' > $STATUS
echo ----------------------------------------------------------- >> $LOG
echo `date` : Bot started >> $LOG
echo ----------------------------------------------------------- >> $LOG
stdbuf -o 0 python /shared/pywikipedia/core/scripts/archivebot.py -log:main.log "Bruker:ArkivBot/autoarkivering" 2>&1 | tee -a $LOG
echo ----------------------------------------------------------- >> $LOG
echo `date` : Bot finished >> $LOG
echo ----------------------------------------------------------- >> $LOG

echo 'false' > $STATUS
